### PR TITLE
fix barrier data-insert error

### PR DESCRIPTION
**Pull request by StandHeo**
when first compensate inserted with db fatal error,the db connection will be closed,and the transaction will not work. then the next opt will be inserted with no transaction,no rollback. so there is a result that the actual business call will not be called.

### CODE REVIEW

**Review by catcherwong — CHANGES_REQUESTED** [review]
**.DS_Store**  should not be commited

**Comment by catcherwong** [comment]
Should update **Dtmgrpc.Tests.BranchBarrierTests.Should_Throw_If_Sql_Execution_Failed** as well.

**Comment by StandHeo** [comment]
resolve unit error and rm .DS_Store file

**Comment by catcherwong** [comment]
image

Also contains .DS_Store file

**Comment by StandHeo** [comment]
rm all .DS_Store file in subDir and commited

**Review by catcherwong — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
